### ISSUE TITLE
Is modality feature extractor available?

### ISSUE THREAD

**Issue by MatheusMMatos** [Exploration-Lab/COGMEN#2]
Congratulation for your work!. and may I ask if you could provide scripts of the extractor feature that produce .pkl files?
Thank you!

**Comment by iabhinavjoshi** [comment]
@MatheusMMatos Thank you for your interest. :)

We followed the scripts provided by the following repositories 
https://github.com/soujanyaporia/multimodal-sentiment-analysis
https://github.com/declare-lab/multimodal-deep-learning

They provide a detailed pipeline for feature extraction set along with the explanation for multiple datasets like MOSI, MOSEI, and IEMOCAP datasets.
